#!/bin/bash


PS3='Choose an Option:' #Shows top of menu
options=("Updates" "Software" "Tweaks" "Themes" "Login Background Image" "All" "Quit" "About") # As opcoes do menu
select opt in "${options[@]}" #le as opcoes possiveis 
do
    case $opt in # 
        "Updates")
       wget -q --tries=10 --timeout=20 --spider http://google.com # Teste de ligação à internet 
	if [[ $? -eq 0 ]]; then # if para saber o resultado e se for positivo o programa avança, se for negativo ele para
		 echo 'Internet connection successfully established'
		 if  sudo apt-get update -y && sudo apt-get upgrade -y; #Fazer os updates	    
        then
    	    	printf 'Updates Completed with success.\n'
	    		else
    	    			printf 'Failed to Update.\n'
	fi
	
	else
		echo "There is no internet connection. Try later"
		break;
		
		
	fi
       
            
            ;;
        "Software")
         wget -q --tries=10 --timeout=20 --spider http://google.com # Teste de ligação à internet 
	if [[ $? -eq 0 ]]; then # if para saber o resultado e se for positivo o programa avança, se for negativo ele para
		 echo 'Internet connection successfully established'
		 if sudo apt install obs-studio conky mpv  pavucontrol git -y #instalação dos diversos programas 
		 wget -O ~/skype.deb https://repo.skype.com/latest/skypeforlinux-64.deb
		 dpkg -i ~/skype.deb
	  then 
          	printf ' Software successfully installed.\n'
          	echo 'Copy and paste conky.conf to folder etc/conky/'
          	
          	read -n 1 -s -r -p " " #Espera por qualquer tecla para continuar
          		else
          			printf 'One or more aplications were not installed.\n'
       fi
		 else 
		echo "There is no internet connection. Try later"
		break;
       
	fi
            ;;
        "Tweaks")
        
         wget -q --tries=10 --timeout=20 --spider http://google.com
	if [[ $? -eq 0 ]]; then
		 echo 'Internet connection successfully established'
		  if sudo apt install gnome-tweak-tool -y
          then
          	printf 'Aplication successfully installed.\n' 
          	            printf "You'll have to install gnome extention shell on firefox and add the following extentions\n - Control Blur Effect On Lock Screen \n - DesktopIcons \n - Dynamic Panel Transparency \n - Hide Activities Button \n - Remove Alt+Tab Delay"
				echo  # Isto ira mover o proximo texto para a proxima linha.
				read -n 1 -s -r -p " " #Espera por qualquer tecla para continuar
          		else 
          			printf 'Gnome Tweak Tool failed to install.\n'
          fi
		 else 
		echo "There is no internet connection. Try later"
		break;
		fi
            ;;
        "Themes")
         wget -q --tries=10 --timeout=20 --spider http://google.com
	if [[ $? -eq 0 ]]; then
		 echo 'Internet connection successfully established'
		    cd Downloads
          if git clone https://github.com/Jannomag/Yaru-Colors.git
            then 
                 printf 'Download completed successfuly.\n'
                 	elif sudo apt install git && git clone https://github.com/Jannomag/Yaru-Colors.git
                 	then
                 		printf 'Git successfully Downloaded and Installed\nOne or more files successfully Donwloaded.'
                 			else 
                 				printf 'Download Failed.\n'
         fi
	cd
           
		 else 
		echo "There is no internet connection. Try later"
		break;
		fi
          ;;
        "Login Background Image")
         wget -q --tries=10 --timeout=20 --spider http://google.com
	if [[ $? -eq 0 ]]; then
		 echo 'Internet connection successfully established'
		 cd Downloads
        if sudo apt install libglib2.0-dev-bin -y 
          then 
          	printf'Libglib2.0-dev-bin successfully installed\n'
          	if git clone https://github.com/thiggy01/ubuntu-20.04-change-gdm-background/raw/master/ubuntu-20.04-change-gdm-background
            then 
                 printf 'Change GDM Background successfully Downloaded.\n'
                 	elif sudo apt install git && git clone https://github.com/thiggy01/ubuntu-20.04-change-gdm-background/raw/master/ubuntu-20.04-change-gdm-background
                 	then
                 		printf'Git Installation and Cloning successfuly completed\n'
                 		 
                 			else 
                 				printf'Failed to Download\n'
               fi
          	      		else 
          			printf'Failed to Download\\n'
       fi
	cd Downloads/ubuntu-20.04-change-gdm-background-master
	chmod +x ubuntu-20.04-change-gdm-background
	cd

		 else 
		echo "There is no internet connection. Try later"
		
		break;
		fi
                    ;;  
        "All")
         wget -q --tries=10 --timeout=20 --spider http://google.com
	if [[ $? -eq 0 ]]; then
		 echo 'Internet connection successfully established'
		  sudo apt-get update -y 
	   sudo apt-get upgrade -y
	   sudo apt install skype obs-studio conky mpv pavucontrol git -y
	   sudo apt install gnome-tweak-tool -y
	   printf "You'll have to install gnome extention shell on firefox and add the following extentions\n - Control Blur Effect On Lock Screen \n - DesktopIcons \n - Dynamic Panel Transparency \n - Hide Activities Button \n - Remove Alt+Tab Delay"
	   echo  # Isto ira mover o proximo texto para a proxima linha.
	   read -n 1 -s -r -p " "
	   cd Downloads
	   sudo apt install git
	git clone https://github.com/Jannomag/Yaru-Colors.git
	   sudo apt install libglib2.0-dev-bin -y
	
	git clone  github.com/thiggy01/ubuntu-20.04-change-gdm-background/raw/master/ubuntu-20.04-change-gdm-background
	   cd Downloads/ubuntu-20.04-change-gdm-background-master
	   chmod +x ubuntu-20.04-change-gdm-background
	   cd
	   cd Downloads/Yaru-Colors-master
	   ./install.sh
	   cd

		 else 
		echo "There is no internet connection. Try later"
		break;
		fi
		;;
                  "Quit")
          printf "Software made by Diogo Queimado.\n"
	   echo  'Press Any Key To Continue:'
	   read -n 1 -s -r -p " "
            break;
            ;; 
        "About")
        	printf "Software made by Diogo Queimado\n"
        	printf "Version 1.1\n"
        	;;
        *) printf "Invalid Option, please choose an option from 1 to 8.\n"
   
            ;;
    esac
done
