#!/bin/bash


PS3='Choose an Option:' #Shows top of menu
options=("Updates" "Software" "Tweaks" "Themes" "Login Background Image" "All" "Quit" "About") # Shows menu options
select opt in "${options[@]}" #read possible options
do
    case $opt in 
        "Updates")
       wget -q --tries=10 --timeout=20 --spider http://google.com # Internet connection test
	if [[ $? -eq 0 ]]; then # if the internet connection is successful the program continues if it fails it stops
		 echo 'Internet connection successfully established'
		 if  sudo apt-get update -y && sudo apt-get upgrade -y; #Doing the updates 	    
        then
    	    	printf 'Updates Completed with success.\n'
	    		else
    	    			printf 'Failed to Update.\n'
	fi
	
	else
		echo "There is no internet connection. Try later"
		break;
		
		
	fi
       
            
            ;;
        "Software")
         wget -q --tries=10 --timeout=20 --spider http://google.com #  Internet connection test
	if [[ $? -eq 0 ]]; then #  if the internet connection is successful the program continues if it fails it stops
		 echo 'Internet connection successfully established'
		 if sudo apt install obs-studio conky mpv  pavucontrol git -y #Installation of several programs skype is a bit more complicated so it takes more space
		 wget -O ~/skype.deb https://repo.skype.com/latest/skypeforlinux-64.deb
		 sudo dpkg -i ~/skype.deb
	  then 
          	printf ' Software successfully installed.\n'
          	echo 'Copy and paste conky.conf to folder etc/conky/'
          	
          	read -n 1 -s -r -p " " #Waiting for input to continue
          		else
          			printf 'One or more aplications were not installed.\n'
       fi
		 else 
		echo "There is no internet connection. Try later"
		break;
       
	fi
            ;;
        "Tweaks")
        
         wget -q --tries=10 --timeout=20 --spider http://google.com
	if [[ $? -eq 0 ]]; then
		 echo 'Internet connection successfully established'
		  if sudo apt install gnome-tweak-tool -y
          then
          	printf 'Aplication successfully installed.\n' 
          	            printf "You'll have to install gnome extention shell on firefox and add the following extentions\n - Control Blur Effect On Lock Screen \n - DesktopIcons \n - Dynamic Panel Transparency \n - Hide Activities Button \n - Remove Alt+Tab Delay"
				echo  # Makes the text go down a line
				read -n 1 -s -r -p " " #Waiting for input to continue
          		else 
          			printf 'Gnome Tweak Tool failed to install.\n'
          fi
		 else 
		echo "There is no internet connection. Try later"
		break;
		fi
            ;;
        "Themes")
         wget -q --tries=10 --timeout=20 --spider http://google.com
	if [[ $? -eq 0 ]]; then
		 echo 'Internet connection successfully established'
		    cd
		    cd Downloads
          if git clone https://github.com/Jannomag/Yaru-Colors.git # It downloads Yaru-Colors which is a theme a use 
            then 
                 printf 'Download completed successfuly.\n'
                 		cd Yaru-Colors
                 	  	./install.sh
                 	elif sudo apt install git && git clone https://github.com/Jannomag/Yaru-Colors.git # if the previous try fails it will try to install git and re download the files
                 	then
                 		printf 'Git successfully Downloaded and Installed\nOne or more files successfully Donwloaded.'
                 				   cd Yaru-Colors
						   ./install.sh
                 			else 
                 				printf 'Download Failed.\n'
         fi
	cd
           
		 else 
		echo "There is no internet connection. Try later"
		break;
		fi
          ;;
        "Login Background Image")
         wget -q --tries=10 --timeout=20 --spider http://google.com
	if [[ $? -eq 0 ]]; then
		 echo "Internet connection successfully established"
		 cd
		 cd Downloads
        if sudo apt install libglib2.0-dev-bin -y # this script need a specific lib to continue so we need to download it
          then 
          	printf 'Libglib2.0-dev-bin successfully installed\n'
          	if git clone https://github.com/thiggy01/ubuntu-20.04-change-gdm-background # Download the files from github 
          
            then 
                 printf 'Change GDM Background successfully Downloaded.\n'
                 	elif sudo apt install git && git clone https://github.com/thiggy01/ubuntu-20.04-change-gdm-background/raw/master/ubuntu-20.04-change-gdm-background #if the previous try fails it will try to install git and re download the files
                 	then
                 		printf 'Git Installation and Cloning successfuly completed\n'
                 		 
                 			else 
                 				printf'Failed to Download\n'
               fi
          	      		else 
          			printf'Failed to Download\\n'
       fi
	cd ubuntu-20.04-change-gdm-background
	chmod +x ubuntu-20.04-change-gdm-background # Change in permission so that we can execute the file via terminal
	echo "Please insert image location to use with Ubuntu Change GDM Background"
	   read loc
	   sudo ./ubuntu-20.04-change-gdm-background $loc 
	cd

		 else 
		echo "There is no internet connection. Try later"
		
		break;
		fi
                    ;;  
        "All")
         wget -q --tries=10 --timeout=20 --spider http://google.com
	if [[ $? -eq 0 ]]; then
		 echo 'Internet connection successfully established'
		  sudo apt-get update -y 
	   sudo apt-get upgrade -y
	   sudo apt install obs-studio conky mpv pavucontrol git -y
	   wget -O ~/skype.deb https://repo.skype.com/latest/skypeforlinux-64.deb
	   sudo dpkg -i ~/skype.deb
	   sudo apt install gnome-tweak-tool -y
	   printf "You'll have to install gnome extention shell on firefox and add the following extentions\n - Control Blur Effect On Lock Screen \n - DesktopIcons \n - Dynamic Panel Transparency \n - Hide Activities Button \n - Remove Alt+Tab Delay"
	   echo  # This will make text go to next line
	   read -n 1 -s -r -p " " #Waiting for user input
	   cd Downloads
	   sudo apt install git
		git clone https://github.com/Jannomag/Yaru-Colors.git
	   sudo apt install libglib2.0-dev-bin -y
	
	git clone  https://github.com/thiggy01/ubuntu-20.04-change-gdm-background.git
	   cd ubuntu-20.04-change-gdm-background
	   chmod +x ubuntu-20.04-change-gdm-background #change of permission so we can execute file in terminal
	   echo "Please insert image location to use with Ubuntu Change GDM Background"
	   read loc
	   sudo ./ubuntu-20.04-change-gdm-background $loc 
	   cd ..
	   cd Yaru-Colors
	   ./install.sh
	   cd

		 else 
		echo "There is no internet connection. Try later"
		break;
		fi
		;;
                  "Quit")
          printf "Software made by Diogo Queimado.\n"
	   echo  'Press Any Key To Continue:'
	   read -n 1 -s -r -p " "
            break;
            ;; 
        "About")
        	printf "Software made by Diogo Queimado\n"
        	printf "Version 1.3\n"
        	;;
        *) printf "Invalid Option, please choose an option from 1 to 8.\n"
   
            ;;
    esac
done
